import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const roboto = Roboto({
  weight: ['300', '400', '500', '600', '700', '900'], // choose the weights you need
  subsets: ['latin'],             // choose the character subsets
  variable: '--font-roboto'       // optional CSS variable
})

export const metadata: Metadata = {
  title: "Akeera",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
       <Header />
        {children}  
        <Footer />
      </body>
    </html>
  )
}

